export const Message = {
  REQUIRED_AUTHORIZATION: 'Authorization header is required',
  INVALID_AUTHORIZATION: 'Invalid Authorization header',
  INVALID_USER: 'Invalid User details',
  RECORD_DOES_NOT_EXIST: 'An error occurred. Record does not exist.',
  RECORD_ALREADY_EXIST: 'An error occurred. Record already exists',
  SUCCESSFUL_REGISTRATION: 'Registration Successful',
  ACCOUNT_EXISTS: 'Account already exists! Try to login instead',
  INVALID_LOGIN_CRED: 'Invalid login credentials',
  SUCCESSFUL_LOGIN: 'successfully logged in',
  EXPIRED_OTP: 'OTP has expired',
  USER_NOT_FOUND: 'User not found',
  INVALID_OTP: 'Invalid OTP',
  PHONE_EXIST: 'User with the phone already exist',
  EMAIL_EXIST: 'User with the email already exist',
  EMAIL_ALREADY_VERIFIED: 'Email already verified',
  EMAIL_VERIFIED: 'Email verified successfully',
  EMAIL_VERIFICATION_RESENT: 'Email verification resent successfully',
  GENERAL_ERROR: 'An error occurred. Try again later',
  EMAIL_IS_REQUIRED: 'Email is required',
  NO_PERMISSION_TO_DELETE_AUDIO:
    'You do not have permission to delete this Audio',
  UNIQUE_TABLE_PRISMA_ERROR:
    "Cannot create duplicate data on table row with 'unique' constraints",
  RESET_PASSWORD: 'Kindly reset your password',
  USERS_ADDED_TO_MAILING_LIST: 'Users added to mailing list',
  EMAIL_UPDATED: 'Email updated successfully',
  USERNAME_IS_TAKEN: 'Username is already taken',
  ACCOUNT_DELETED: 'Account deleted successfully',
  CREATE_ACCOUNT:
    'oops! Seems you do not have an account yet. Click on register to create account',
  INVALID_PHONE: 'Invalid Phone number',
  INVALID_FOLLOWEE: 'Followee account does not exist',
  CANNOT_FOLLOW_SELF: 'You cannot follow nor unfollow yourself',
  INCORRECT_PASSWORD: 'Incorrect Password',
  RECOVERY_OTP_SENT: 'Recovery OTP sent',
  SUCCESSFUL_PASSWORD_RESET: 'Password reset complete',
  PASSWORD_UPDATED: 'Password updated successfully',
  OTP_SENT: 'OTP sent',
  SUCCESSFUL_VERIFICATION: 'Verification Successful',
  KYC_ALREADY_COMPLETED: 'User KYC already completed.',
  KYC_COMPLETED: 'User KYC completed successfully.',
  ONLY_KYC_USER_CAN_REDEEM: 'Only KYC verified users can redeem',
  SUCCESSFUL_USER_DATA: 'Users data fetched successfully',
  SUCCESSFUL_SPECIALTY_UPDATE: 'User specialty updated successfully',
  SUCCESSFUL_INTEREST_UPDATE: 'Successfully updated user Interests',
  SUCCESSFUL_PROFILE_SETUP: 'User profile successfully set up',
  PHONE_AND_EMAIL_NOT_VERIFIED: 'Phone and Email not verified.',
  ADMIN_STATISTICS: 'admin statistics fetched successfully',
  FETCH_ALL_USERS: 'fetched all users successfully',
  ADMIN_CREATED: 'Admin created successfully',
  SUCCESSFUL_ROLE_UPDATE: 'Role updated successfully',
  FAILED_TO_UPDATE_AVATAR: 'Failed to update Avatar, try again later',
  AVATAR_UPLOAD: 'Successfully updated avatar',
  PROFILE_NOT_COMPLETED: 'Profile not completed',
  AVATAR_NOT_UPDATED: 'Avatar not updated',
  NOTIFICATION_SENT: 'Notification sent successfully',
  FAILED_TO_SEND_NOTIFICATION: 'Failed to send notification',
  NOTIFICATION_STATUS: 'Notification status updated',
  NOTIFICATION_DETAILS: 'Users notification data',
  NOTIFICATION_NOT_FOUND: 'Notification not found',
  USERNAME_UPDATED: 'Username successfully updated to <USERNAME>',
  USER_TRANSACTION_PIN_STATUS_FETCHED:
    'User transaction pin status fetched successfully.',
  USER_TRANSACTION_PIN_SET: 'User transaction pin set successfully.',
  USER_HAS_TRANSACTION_PIN: 'User has transaction pin',
  USER_TRANSACTION_PIN_UPDATED: 'User transaction pin updated successfully.',
  NO_TRANSACTION_PIN: 'User has no transaction pin',
  OLD_TRANSACTION_PIN_INCORRECT: 'Old transaction pin is incorrect',
  NEW_TRANSACTION_PIN_SAME_AS_OLD: 'New transaction pin is same as old',
  INCORRECT_TRANSACTION_PIN: 'User transaction pin is incorrect',
  NGN_TRANSACTION_SUCCESSFUL: 'NGN transaction successful',
  INSUFFICIENT_FUND: 'Insufficient balance',
  WALLET_EXISTS: 'Wallet already exists',
  CURRENCY_EXISTS: 'Currency already exist',
  NO_CURRENCY_FOUND: 'Currency not found',
  WALLET_NOT_FOUND: 'Wallet not found',
  NO_NEGATIVE_PAGE_VALUE: 'Page value cannot be negative',
  UNSUPPORTED_CURRENCY: 'Unsupported currency',
  WALLET_CURRENCY_CREATED: 'Wallet currency created successfully.',
  WALLET_CURRENCY_UPDATED: 'Wallet currency updated successfully.',
  WALLET_CURRENCY_DELETED: 'Wallet currency deleted successfully.',
  COWRIES_WALLET_NOT_FOUND: 'User cowries wallet not found',
  NO_NGN_WALLET: '<USER> does not have a NGN wallet',
  AVAILABLE_WALLET_FETCHED: 'Available wallets fetched successfully.',
  SWAP_PAIRS_FETCHED: 'Swap pairs fetched successfully.',
  USER_WALLET_CREATED: 'User wallet created successfully.',
  USER_WALLET_FETCHED: 'User wallets fetched successfully.',
  TRANSACTION_HISTORY_FETCHED: 'Transaction history fetched successfully',
  EXCHANGE_RATE_SET: 'Exchange rate set successfully.',
  EXCHANGE_RATE_FETCHED: 'Exchange rate fetched successfully.',
  webhookDataReceived: 'Webhook data received successfully',
  NO_RESOURCE_FOUND: 'No resource found',
  ACCOUNT_NOT_FOUND:
    'Oops! No account found for this email. Please check or sign up.',
  VENDORS_FETCHED: 'Vendors fetched successfully',
  VENDOR_FETCHED: 'Vendor fetched successfully',
  VENDOR_NOT_FOUND: 'Vendor not found',
  CLIENT_CREATED: 'Client created successfully',
  CLIENT_FETCHED: 'Client Fetched',
  CLIENT_NOT_FOUND: 'Client not found',
  CLIENT_EXISTS: 'Client already exists',
  INVOICE_CREATED: 'Invoice created successfully',
  INVOICE_FETCHED: 'Invoice fetched successfully',
  INVOICE_NOT_FOUND: 'Invoice not found',
  INVOICE_UPDATED: 'Invoice updated successfully',
  INVOICE_STATISTICS: 'Invoice statistics fetched successfully',
  INVOICE_DELETED: 'Invoice deleted successfully',
  INVOICE_SENT: 'Invoice sent successfully',
  INVOICE_MARKED_AS_PAID: 'Invoice marked as paid successfully',
  CLIENT_DELETED: 'Client deleted successfully',
  CLIENT_UPDATED: 'Client updated successfully',
  INVOICE_SEARCH_RESULT: 'Invoice search result',
  TRANSACTION_PIN_VERIFIED: 'Transaction pin verified successfully',
  WRONG_REQUEST: 'Wrong request',
  BANK_LIST_FETCHED: 'Bank list fetched successfully',
  ACCOUNT_FETCHED: 'Account fetched successfully',
  INVALID_ACCOUNT_NUMBER: 'Invalid account number',
  PROCESSING_TRANSACTION: 'Processing transaction',
  MONEY_WITHDRAWN: 'Money withdrawn from wallet',
  MINIMUM_WITHDRAWAL: 'Minimum withdrawal is amount NGN <AMOUNT>',
  SIGNATURE_MISMATCH: 'Signature mismatch',
  PROCESSING_WITHDRAWAL: 'Processing withdrawal',
  NO_RESOURCE: 'No resource found',
  PAYMENT_RECEIVED: 'Payment received from <USER>',
  TRANSACTION_NOT_FOUND: 'Transaction not found',
  WITHDRAWAL_FAILED: 'Withdrawal failed',
  ACTIVITY_LOGS_FETCHED: 'Activity logs fetched successfully',
} as const;
